name = "img2nc"
version = "1.1.0"
license = "MIT"
author = "Shinobu Amasaki"
maintainer = "amasaki203@gmail.com"
copyright = "Copyright 2022, Shinobu Amasaki"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
external-modules = ["netcdf"]
link = ["m", "netcdff"] # DON'T change the order for ifort

[install]
library = false