name = "img2nc"
version = "0.1.0"
license = "MIT"
author = "Shinobu Amasaki"
maintainer = "amasaki203@gmail.com"
copyright = "Copyright 2022, Shinobu Amasaki"
# [library]
# include-dir = ["include"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
external-modules = "netcdf"
link = "netcdff"

[install]
library = false