name = "img2nc"
version = "2.0.0"
license = "MIT"
author = "Shinobu Amasaki"
maintainer = "amasaki203@gmail.com"
copyright = "Copyright 2022, Shinobu Amasaki"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
external-modules = ["netcdf", "mpi_f08"]
link = ["m", "netcdff"] # DON'T change the order for ifort

[install]
library = false


[[executable]]
name = 'img2nc-mola'
main = 'main-mola.f90'

[[executable]]
name = 'mola-trim'
main = 'main-mola-trim.f90'