module keys_m
   implicit none
   private
   
   character(14), parameter, public :: PDS_VERSION_ID         = 'PDS_VERSION_ID' 
   character(11), parameter, public :: RECORD_TYPE            = 'RECORD_TYPE'
   character( 9), parameter, public :: FILE_NAME              = 'FILE_NAME'
   character( 9), parameter, public :: HAT_IMAGE              = '^IMAGE'
   character(12), parameter, public :: MISSION_NAME           = 'MISSION_NAME'
   character(11), parameter, public :: DATA_SET_ID            = 'DATA_SET_ID'
   character(13), parameter, public :: DATA_SET_NAME          = 'DATA_SET_NAME'
   character(16), parameter, public :: L2DB_ORIGINAL_ID       = 'L2DB_ORIGINAL_ID'
   character(10), parameter, public :: PRODUCT_ID             = 'PRODUCT_ID'
   character(15), parameter, public :: INSTRUMENT_TYPE        = 'INSTRUMENT_TYPE'
   character(13), parameter, public :: INSTRUMENT_ID          = 'INSTRUMENT_ID'
   character(15), parameter, public :: INSTRUMENT_NAME        = 'INSTRUMENT_NAME'
   character(20), parameter, public :: INSTRUMENT_HOST_NAME   = 'INSTRUMENT_HOST_NAME'
   character(11), parameter, public :: TARGET_TYPE            = 'TARGET_TYPE'
   character(11), parameter, public :: TARGET_NAME            = 'TARGET_NAME'
   character(10), parameter, public :: START_TIME             = 'START_TIME'
   character( 9), parameter, public :: STOP_TIME              = 'STOP_TIME' 
   character(13), parameter, public :: SOFTWARE_NAME          = 'SOFTWARE_NAME'
   character(16), parameter, public :: SOFTWARE_VERSION       = 'SOFTWARE_VERSION'
   character(18), parameter, public :: PROCESS_VERSION_ID     = 'PROCESS_VERSION_ID'
   character(21), parameter, public :: PRODUCT_CREATION_TIME  = 'PRODUCT_CREATION_TIME'
   character(11), parameter, public :: PRODUCER_ID            = 'PRODUCER_ID'
   character(14), parameter, public :: PRODUCT_SET_ID         = 'PRODUCT_SET_ID'
   character(18), parameter, public :: PRODUCT_VERSION_ID     = 'PRODUCT_VERSION_ID'
   character(19), parameter, public :: UPPER_LEFT_LATITUDE    = 'UPPER_LEFT_LATITUDE'
   character(20), parameter, public :: UPPER_LEFT_LONGITUDE   = 'UPPER_LEFT_LONGITUDE'
   character(20), parameter, public :: UPPER_RIGHT_LATITUDE   = 'UPPER_RIGHT_LATITUDE'
   character(21), parameter, public :: UPPER_RIGHT_LONGITUDE  = 'UPPER_RIGHT_LONGITUDE'
   character(19), parameter, public :: LOWER_LEFT_LATITUDE    = 'LOWER_LEFT_LATITUDE'
   character(20), parameter, public :: LOWER_LEFT_LONGITUDE   = 'LOWER_LEFT_LONGITUDE'
   character(20), parameter, public :: LOWER_RIGHT_LATITUDE   = 'LOWER_RIGHT_LATITUDE'
   character(21), parameter, public :: LOWER_RIGHT_LONGITUDE  = 'LOWER_RIGHT_LONGITUDE'
   character(21), parameter, public :: IMAGE_CENTER_LATITUDE  = 'IMAGE_CENTER_LATITUDE'
   character(22), parameter, public :: IMAGE_CENTER_LONGITUDE = 'IMAGE_CENTER_LONGITUDE'
   ! Followings are defined in MOLA's lbl file:
   character(12), parameter, public :: FILE_RECORDS           = 'FILE_RECORDS'   
   character(12), parameter, public :: RECORD_BYTES           = 'RECORD_BYTES'   
   character(15), parameter, public :: SPACECRAFT_NAME        = 'SPACECRAFT_NAME'
   character(18), parameter, public :: START_ORBIT_NUMBER     = 'START_ORBIT_NUMBER'
   character(17), parameter, public :: STOP_ORBIT_NUMBER      = 'STOP_ORBIT_NUMBER'
   character(18), parameter, public :: PRODUCER_FULL_NAME     = 'PRODUCER_FULL_NAME'
   character(25), parameter, public :: PRODUCER_INSTITUTION_NAME = 'PRODUCER_INSTITUTION_NAME'
   character(11), parameter, public :: DESCRIPTION            = 'DESCRIPTION'


   ! OBJECT = IMAGE_MAP_PROJECTION
   character(24), parameter, public :: HAT_DATA_SET_MAP_PROJECTION   = '^DATA_SET_MAP_PROJECTION' 
   character(19), parameter, public :: MAP_PROJECTION_TYPE           = 'MAP_PROJECTION_TYPE'
   character(22), parameter, public :: COORDINATE_SYSTEM_TYPE        = 'COORDINATE_SYSTEM_TYPE'
   character(22), parameter, public :: COORDINATE_SYSTEM_NAME        = 'COORDINATE_SYSTEM_NAME'
   character(13), parameter, public :: A_AXIS_RADIUS                 = 'A_AXIS_RADIUS'
   character(13), parameter, public :: B_AXIS_RADIUS                 = 'B_AXIS_RADIUS'
   character(13), parameter, public :: C_AXIS_RADIUS                 = 'C_AXIS_RADIUS'
   character(23), parameter, public :: FIRST_STANDARD_PARALLEL       = 'FIRST_STANDARD_PARALLEL'
   character(24), parameter, public :: SECOND_STANDARD_PARALLEL      = 'SECOND_STANDARD_PARALLEL'
   character(28), parameter, public :: POSITIVE_LONGITUDE_DIRECTION  = 'POSITIVE_LONGITUDE_DIRECTION'
   character(15), parameter, public :: CENTER_LATITUDE               = 'CENTER_LATITUDE'
   character(16), parameter, public :: CENTER_LONGITUDE              = 'CENTER_LONGITUDE'
   character(18), parameter, public :: REFERENCE_LATITUDE            = 'REFERENCE_LATITUDE'
   character(19), parameter, public :: REFERENCE_LONGITUDE           = 'REFERENCE_LONGITUDE'
   character(16), parameter, public :: LINE_FIRST_PIXEL              = 'LINE_FIRST_PIXEL'
   character(15), parameter, public :: LINE_LAST_PIXEL               = 'LINE_LAST_PIXEL'
   character(18), parameter, public :: SAMPLE_FIRST_PIXEL            = 'SAMPLE_FIRST_PIXEL'
   character(17), parameter, public :: SAMPLE_LAST_PIXEL             = 'SAMPLE_LAST_PIXEL'
   character(23), parameter, public :: MAP_PROJECTION_ROTATION       = 'MAP_PROJECTION_ROTATION'
   character(14), parameter, public :: MAP_RESOLUTION                = 'MAP_RESOLUTION'
   character( 9), parameter, public :: MAP_SCALE                     = 'MAP_SCALE'
   character(16), parameter, public :: MAXIMUM_LATITUDE              = 'MAXIMUM_LATITUDE'
   character(16), parameter, public :: MINIMUM_LATITUDE              = 'MINIMUM_LATITUDE'
   character(21), parameter, public :: EASTERNMOST_LONGITUDE         = 'EASTERNMOST_LONGITUDE'
   character(21), parameter, public :: WESTERNMOST_LONGITUDE         = 'WESTERNMOST_LONGITUDE'
   character(22), parameter, public :: LINE_PROJECTION_OFFSET        = 'LINE_PROJECTION_OFFSET'
   character(24), parameter, public :: SAMPLE_PROJECTION_OFFSET      = 'SAMPLE_PROJECTION_OFFSET'
   character(17), parameter, public :: RESAMPLING_METHOD             = 'RESAMPLING_METHOD'

   ! OBJECT = PROCESSING_PARAMETERS
   character(18), parameter, public :: PARAMETER_SET_NAME           = 'PARAMETER_SET_NAME'
   character(27), parameter, public :: HORIZONTAL_TRANSFORM_METHOD  = 'HORIZONTAL_TRANSFORM_METHOD'
   character(25), parameter, public :: VERTICAL_TRANSFORM_METHOD    = 'VERTICAL_TRANSFORM_METHOD'
   character(15), parameter, public :: MOSAIC_PRIORITY              = 'MOSAIC_PRIORITY'
   character(15), parameter, public :: SMOOTHING_WIDTH              = 'SMOOTHING_WIDTH'

   character( 5), parameter, public :: BANDS               = 'BANDS'
   character(17), parameter, public :: BAND_STORAGE_TYPE   = 'BAND_STORAGE_TYPE'
   character( 9), parameter, public :: BAND_NAME           = 'BAND_NAME'
   character( 5), parameter, public :: LINES               = 'LINES'
   character(12), parameter, public :: LINE_SAMPLES        = 'LINE_SAMPLES'
   character(11), parameter, public :: SAMPLE_TYPE         = 'SAMPLE_TYPE'
   character(11), parameter, public :: SAMPLE_BITS         = 'SAMPLE_BITS'
   character(16), parameter, public :: IMAGE_VALUE_TYPE    = 'IMAGE_VALUE_TYPE'
   character(15), parameter, public :: SAMPLE_BIT_MASK     = 'SAMPLE_BIT_MASK'
   character(15), parameter, public :: OFFSET              = 'OFFSET'
   character(14), parameter, public :: SCALING_FACTOR      = 'SCALING_FACTOR'
   character(14), parameter, public :: STRETCHED_FLAG      = 'STRETCHED_FLAG'
   character(13), parameter, public :: VALID_MINIMUM       = 'VALID_MINIMUM'
   character(13), parameter, public :: VALID_MAXIMUM       = 'VALID_MAXIMUM'
   character( 5), parameter, public :: DUMMY               = 'DUMMY'
   character( 7), parameter, public :: MINIMUM             = 'MINIMUM'
   character( 7), parameter, public :: MAXIMUM             = 'MAXIMUM'
   character( 7), parameter, public :: AVERAGE             = 'AVERAGE'
   character( 5), parameter, public :: STDEV               = 'STDEV'
   character(10), parameter, public :: MODE_PIXEL          = 'MODE_PIXEL'
   character( 4), parameter, public :: UNIT                = 'UNIT'
   character( 4), parameter, public :: NAME                = 'NAME'

   ! OBJECT = QUALITY_INFO
   character(21), parameter, public :: QA_PERCENT_GOOD_PIXEL           = 'QA_PERCENT_GOOD_PIXEL'
   character(22), parameter, public :: QA_PERCENT_DUMMY_PIXEL          = 'QA_PERCENT_DUMMY_PIXEL'
   character(20), parameter, public :: QA_PERCENT_BAD_PIXEL            = 'QA_PERCENT_BAD_PIXEL'
   character(29), parameter, public :: QA_PERCENT_INTERPOLATED_PIXEL   = 'QA_PERCENT_INTERPOLATED_PIXEL'
   character(23), parameter, public :: QA_PERCENT_SHADOW_PIXEL         = 'QA_PERCENT_SHADOW_PIXEL'
   character(30), parameter, public :: BADPIXEL_THRESHOLD_CORRELATION  = 'BADPIXEL_THRESHOLD_CORRELATION'
   character(25), parameter, public :: BAD_PIXEL_THRESHOLD_SLOPE       = 'BAD_PIXEL_THRESHOLD_SLOPE'

end module keys_m